#ifndef _SERIAL_PROTOCOL_H_
#define _SERIAL_PROTOCOL_H_

#define MESSAGE_TERMINATION "\r\n"
#define LOG_COMMAND_PREFIX "LOG "

// Reason codes
#define REASON_CODE_OK 0
#define REASON_CODE_UNKNOWN_OPTION 1
#define REASON_CODE_MISSING_MANDATORY_OPTION 2
#define REASSON_CODE_INVALID_OPTION 3

#endif